release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  dependencies:
    - upload-binaries
  extends:
    - .rules:release:all
  script:
    - apk add make bash curl
    - make release

release-oci:
  stage: release
  image: golang:$GO_VERSION-alpine
  variables:
    COSIGN_YES: "true"
  id_tokens:
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  dependencies:
    - binaries
  extends:
    - .rules:release:all
  script:
    - apk add --update make cosign git bash
    - make release-oci-artifacts
